#!/bin/bash
# file: reset_dns.bash


sudo echo -e "[network]\ngenerateResolvConf = false" >> /etc/wsl.conf

echo -n "Enter new dns-server: "
read new_dns
sudo rm /etc/resolv.conf
sudo touch /etc/resolv.conf
sudo echo -e "# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:># [network]\n# generateResolvConf = false" > /etc/resolv.conf
sudo echo "options timeout:0.1" >> /etc/resolv.conf

if [[ $new_dns ]]; then
  sudo echo "nameserver $new_dns" >> /etc/resolv.conf
fi

sudo echo "nameserver 192.168.2.1" >> /etc/resolv.conf
sudo echo "nameserver 8.8.8.8" >> /etc/resolv.conf
sudo echo "nameserver 10.174.0.8" >> /etc/resolv.conf
sudo echo "nameserver 10.174.0.40" >> /etc/resolv.conf
sudo echo "nameserver 192.168.240.1" >> /etc/resolv.conf
